import Header from "@/components/Header";
import "./globals.css";
import Providers from "./Providers";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: 'Rg Next App',
  description: 'Generated by create Rg app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {/* HEADER */}
           <Header />
        
          {/* NAVBAR */}
           <Navbar />

          {/* SEARCH BOX */}
          {children}
        </Providers> 
      </body>
    </html>
  )
}
