import Header from "@/components/Header";
import "./globals.css";

export const metadata = {
  title: 'Rg Next App',
  description: 'Generated by create Rg app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* HEADER */}
        <Header />
        
        {/* NAVBAR */}

        {/* SEARCH BOX */}
        {children}
      </body>
    </html>
  )
}
