import "./globals.css";

export const metadata = {
  title: 'Rg Next App',
  description: 'Generated by create Rg app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
